package games.moisoni.google_iab.enums;

public enum ErrorType {
    CLIENT_NOT_READY,
    CLIENT_DISCONNECTED,
    SKU_NOT_EXIST,
    CONSUME_ERROR,
    ACKNOWLEDGE_ERROR,
    ACKNOWLEDGE_WARNING,
    FETCH_PURCHASED_PRODUCTS_ERROR,
    BILLING_ERROR,
    USER_CANCELED,
    SERVICE_UNAVAILABLE,
    BILLING_UNAVAILABLE,
    ITEM_UNAVAILABLE,
    DEVELOPER_ERROR,
    ERROR,
    ITEM_ALREADY_OWNED,
    ITEM_NOT_OWNED,
}