package games.moisoni.google_iab.enums;

public enum ErrorType {
    CLIENT_NOT_READY,
    CLIENT_DISCONNECTED,
    ITEM_NOT_EXIST,
    ITEM_ALREADY_OWNED,
    CONSUME_ERROR,
    ACKNOWLEDGE_ERROR,
    ACKNOWLEDGE_WARNING,
    FETCH_PURCHASED_PRODUCTS_ERROR,
    BILLING_ERROR
}